language: minimal

services:
  - docker

env:
  - CONTAINER=hyperkube-iscsi

script:
  - echo ${TRAVIS_REPO_SLUG} | cut -d '/' -f 1
  - docker build -t $(echo ${TRAVIS_REPO_SLUG} | cut -d '/' -f 1)/$CONTAINER $CONTAINER/
